### ISSUE TITLE
toolchain_container cannot use 2 http_files for keys

### ISSUE THREAD

**Issue by Dig-Doug** [bazelbuild/rules_docker#1287] opened 2019-11-19 05:45 UTC
Hi, I'm trying to use 2 downloaded gpg keys with `toolchain_container` but I am seeing an error. I think the problem is that the two keys are being added to the image under the same name and thus being overwritten.

This is a warning I see:

```
INFO: From ImageLayer with_deps_with_keys.key-layer.tar:
Duplicate file in archive: ./gpg/downloaded, picking first occurrence
```

I've created a reproduction [here](https://github.com/Dig-Doug/rules_docker_bug)

Steps to reproduce:

```
cd /tmp
git clone https://github.com/Dig-Doug/rules_docker_bug.git
cd rules_docker_bug
git checkout 43183c006c314b2872ea6ee46144654b072c07c5
bazel build //:with_deps

# See error

vim BUILD.bazel
# Comment out either all docker configs or llvm configs

bazel build //:with_deps
# Build should pass
# This means that each config is correct on it's own, but when combined it fails.
```

Please let me know if you need more information. Thanks!

**Comment by nlopezgi** [comment] 2019-11-19 15:00
The issue you are seeing here is that the two keys downloaded via `http_file` rule have the same file name, and mounting them in the container results in one overriding the other.
The solution is to use `downloaded_file_path` attr of `http_file` for the gpgkey files.  Example:
https://github.com/GoogleCloudPlatform/layer-definitions/blob/master/WORKSPACE#L78.

Let me know if the issue persists, but I'm pretty sure we also had that issue for the repo above and solved as indicated. Closing for now.

**Comment by Dig-Doug** [comment] 2019-11-19 15:33
Thanks for pointing out `downloaded_file_path`, didn't know about that.

However, personally I would've expected that the rule be able to handle this case since they are different targets and the files would have unique paths. I haven't tried it, but I would guess that if you had a setup using keys `lib1/key.gpg` and `lib2/key.gpg`, you'd have the same issue.

Alternatively, the rule could throw an error because the user probably isn't trying to duplicate keys.

**Comment by nlopezgi** [comment] 2019-11-19 16:03
The rule just passes down the given files to create a container. The problem is the default http_file produces, by default, a file with the same name in different external repos. To do this differently you would have to deal with the name of the external repo in some way when mounting the key files, probably somewhere around [here](https://github.com/bazelbuild/rules_docker/blob/master/docker/package_managers/apt_key.bzl#L76), and set up tests. I'm happy to work with you if you want to send a PR to fix this.

Reopening in case anyone wants to contribute to improve this.

**Closed** 2021-04-18 02:09 UTC
Labels: Can Close?
