### ISSUE TITLE
nodejs_image doesn't work when building on macOS

### ISSUE THREAD

**Issue by jfirebaugh** [bazelbuild/rules_docker#1853] opened 2021-05-18 19:08 UTC
# 🐞 bug report

### Affected Rule

The issue is caused by the rule: `nodejs_image`

### Is this a regression?

Probably not.

### Description

I attempted to use the `nodejs_image` rule, building on macOS 11.3.1. When I run `bazel run :image`, I receive the following output from docker:

```
ERROR[runfiles.bash]: cannot look up runfile "nodejs_linux_amd64/bin/nodejs/bin/node"  (RUNFILES_DIR="/app/deploys/backend_image.binary.runfiles", RUNFILES_MANIFEST_FILE="")

>>>> FAIL: The node binary 'nodejs_linux_amd64/bin/nodejs/bin/node' not found in runfiles.
This node toolchain was chosen based on your uname 'Linux x86_64'.
Please file an issue to https://github.com/bazelbuild/rules_nodejs/issues if 
you would like to add your platform to the supported rules_nodejs node platforms. <<<<
```

Inspecting the layer contents with [dive](https://github.com/wagoodman/dive), I can see that the rule created a layer with the `nodejs_darwin_amd64` node binary from the build host. Obviously this won't work in a linux image.

## 🔬 Minimal Reproduction

https://gist.github.com/jfirebaugh/1128794b0e88bdea3db73474d88f0bb1

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>
macOS 11.3.1
  </code>
</pre>

**Output of `bazel version`:**

<pre>
  <code>
Build label: 4.0.0-homebrew
Build target: bazel-out/darwin-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Sat Jan 23 02:07:47 2021 (1611367667)
Build timestamp: 1611367667
Build timestamp as int: 1611367667
  </code>
</pre>

**Rules_docker version:**

<pre>
  <code>
0.17.0
  </code>
</pre>

**Anything else relevant?**

**Comment by dsilvasc** [comment] 2021-08-06 13:39
duplicate of https://github.com/bazelbuild/rules_docker/issues/1588#issuecomment-699750928 ?

**Closed** 2022-03-05 02:27 UTC
Labels: Can Close?
