### ISSUE TITLE
Docker Images don't run from bazel

### ISSUE THREAD

**Issue by cpenner-va** [bazelbuild/rules_docker#116] opened 2017-08-11 21:19 UTC
## Expected

Running `bazel run //:hello` should print the hello world message

## Actual Behaviour

Running `bazel run //:hello` stalls indefinitely with no output

## Steps to reproduce:

```
#WORKSPACE
git_repository(
    name = "io_bazel_rules_docker",
    remote = "https://github.com/bazelbuild/rules_docker.git",
    tag = "v0.1.0",
)

load(
  "@io_bazel_rules_docker//docker:docker.bzl",
  "docker_repositories", "docker_pull"
)
docker_repositories()

docker_pull(
    name = "helloworld",
    registry = "index.docker.io",
    repository = "library/hello-world",
    tag = "latest",
)
```

```
#BUILD
load("@io_bazel_rules_docker//docker:docker.bzl", "docker_build")

docker_build(name="hello", base="@helloworld//image")
```

```
$ bazel version
Build label: 0.5.3
Build target: bazel-out/darwin_x86_64-fastbuild/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Fri Jul 28 08:34:35 2017 (1501230875)
Build timestamp: 1501230875
Build timestamp as int: 1501230875
```

Now run the following, it stalls indefinitely

```
bazel run //:hello
INFO: Found 1 target...
Target //:hello up-to-date:
  bazel-bin/hello-layer.tar
INFO: Elapsed time: 0.153s, Critical Path: 0.00s

INFO: Running command line: bazel-bin/hello
^[^C
Bazel caught interrupt signal; shutting down.
```

The following DOES work and provides the expected behaviour:
```
$ bazel build //:hello.tar && docker load -i bazel-bin/hello.tar && docker run bazel:server_image
INFO: Found 1 target...
Target //:hello.tar up-to-date:
  bazel-bin/hello.tar
INFO: Elapsed time: 0.131s, Critical Path: 0.00s
Loaded image: bazel:hello

Hello from Docker!
This message shows that your installation appears to be working correctly.

To generate this message, Docker took the following steps:
 1. The Docker client contacted the Docker daemon.
 2. The Docker daemon pulled the "hello-world" image from the Docker Hub.
 3. The Docker daemon created a new container from that image which runs the
    executable that produces the output you are currently reading.
 4. The Docker daemon streamed that output to the Docker client, which sent it
    to your terminal.

To try something more ambitious, you can run an Ubuntu container with:
 $ docker run -it ubuntu bash

Share images, automate workflows, and more with a free Docker ID:
 https://cloud.docker.com/

For more examples and ideas, visit:
 https://docs.docker.com/engine/userguide/

```

**Comment by mattmoor** [comment] 2017-08-11 21:35
We don't currently run the container on `bazel run`, I'm introducing an option to do that in [this PR](https://github.com/bazelbuild/rules_docker/pull/112), and I'm making it the default for `foo_image` language rules; however, for containers that run services, Bazel doesn't propagate the ctrl-C (yet), so I'm leery of making it the default generally until that's fixed.

I'm a bit surprised that `bazel run` hangs indefinitely for you (not a failure mode I've seen).  To wager a guess, since you can successfully build the `.tar` target I'd say you probably have a ton of images in your local daemon, which is making the [incremental load](https://github.com/bazelbuild/rules_docker/blob/master/docker/incremental_load.sh.tpl) script slower than simply linking and loading the tarball.

Out of curiosity, what version of docker are you using?

**Comment by cpenner-va** [comment] 2017-08-14 21:20
```
$ docker version
Client:
 Version:      17.03.1-ce
 API version:  1.27
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Tue Mar 28 00:40:02 2017
 OS/Arch:      darwin/amd64

Server:
 Version:      17.03.1-ce
 API version:  1.27 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Fri Mar 24 00:00:50 2017
 OS/Arch:      linux/amd64
 Experimental: true
```

**Comment by mattmoor** [comment] 2017-08-21 23:17
Does this still hang indefinitely for you?  How many images do you have locally?  e.g. What does `docker images` show?

**Comment by cpenner-va** [comment] 2017-08-22 14:59
I've got about 309 images; not a small amount, but probably not enough to cause problems. I deleted down to 161 and it still stalls.

**Comment by mattmoor** [comment] 2017-08-22 15:04
I wonder if you could try instrumenting [the incremental load script](https://github.com/bazelbuild/rules_docker/blob/master/docker/incremental_load.sh.tpl#L17) with `-x` so we can see the commands it is executing?

**Comment by mattmoor** [comment] 2017-08-22 15:05
You can either clone things locally and switch the `git_repository` import to `local_repository` (what I usually do) or fork the repo and push a small change (and move your `git_repository` to point there).

**Comment by mattmoor** [comment] 2017-09-13 20:55
I'm going to close this for now.  Feel free to re-open if you can provide more information to help reproduce or diagnose the issue.

**Closed by mattmoor** 2017-09-13 20:55 UTC
