### ISSUE TITLE
container_push from contrib/push-all.bzl fails on empty images dict

### ISSUE THREAD

**Issue by stevewolter** [bazelbuild/rules_docker#511] opened 2018-09-03 09:44 UTC
When run on an empty images dict, the container_push fails on some shells with:

line 36: PIDS[@]: unbound variable

I realize that this is a contrib/ file and it's easy enough to work around, so I'm posting this for tracking and don't expect a fix from the maintainers. Thanks for maintaining rules_docker, it's awesome!

**Comment by drigz** [comment] 2018-09-03 12:26
Specifically, it fails with bash 4.3 but works with bash 4.4. It's not clear to me whether bash 4.3 or 4.4 behaves as expected, as the docs in 4.4 suggest that the error should still occur. For more discussion, [see the comments on this SO answer](https://stackoverflow.com/a/7577209).

**Comment by xingao267** [comment] 2018-09-04 22:48
It looks like the push-all.sh.tpl should probably be updated to adapt this.

**Comment by smukherj1** [comment] 2018-09-07 18:09
I locally reproduced this on Ubuntu 16.04 with bash 4.3.48. Verified #516 fixes the issue and does not break on bash 4.4. Also added a test for the empty bundle case to //tests/contrib. Closing this issue. Please  reopen if the fix doesn't work for you

**Closed by smukherj1** 2018-09-07 18:09 UTC
