### ISSUE TITLE
py_image deps/layers discrepancy.

### ISSUE THREAD

**Issue by mattmoor** [bazelbuild/rules_docker#161] opened 2017-09-23 02:42 UTC
If [this line](https://github.com/bazelbuild/rules_k8s/blob/93bf3ead1904a3b0e5c31312718f2aa98abbaac2/examples/hellohttp/py/BUILD#L25) is changed to `layers=[]` instead of `deps=[]` then the image no longer works properly.

**Comment by calder** [comment] 2017-12-30 18:53
To clarify, the problem is that `py_image` requirements in `layers` are not installed on the `PYTHONPATH`. This results in an ImportError when attempting to import the module in the container.

Here is a minimal repro: [repro.tar.gz](https://github.com/bazelbuild/rules_docker/files/1594675/repro.tar.gz)

```sh
➤ bazel run //:hello_image_push; docker rmi -f localhost:5000/hello; docker run -p 1234:1234 localhost:5000/hello
...
Traceback (most recent call last):
  File "/app/hello_image.binary.runfiles/__main__/hello.py", line 1, in <module>
    from flask import Flask
ImportError: No module named flask
```

**Comment by mattmoor** [comment] 2017-12-30 20:54
I haven't had a chance to investigate this.

My intuition is that it is clearly a bug in `py_image` (not `py_binary` or `pip_import`) because they *should* look identical in the resulting filesystem of either `deps` or `layers` and they apparently don't.

One thing to try, which I haven't is whether `layers=[]` works when binary-agnostic paths + symlinks are disabled.  That's the only meaningful / intentional difference I can think of.

**Comment by mattem** [comment] 2019-02-06 22:00
I _think_ I am hitting this issue still. `py_binary` works as expected with `requirement("flask"),` added to `deps`. 
Having this requirement in `layers` on `py_image` causes it not to find the dependency, moving it to `deps` causes it not to find a transitive dependency.

```
py3_image(
    name = "image",
    srcs = ["app.py"],
    deps = [
       requirement("flask"),
    ],
    main = "app.py",
)
```
Results in:
```
Traceback (most recent call last):
  File "/app/ev/tooling/py_flask/image.binary.runfiles/evertz/ev/tooling/py_flask/app.py", line 1, in <module>
    from flask import Flask
  File "/app/ev/tooling/py_flask/image.binary.runfiles/pypi__Flask_1_0_2/flask/__init__.py", line 17, in <module>
    from werkzeug.exceptions import abort
ImportError: No module named 'werkzeug'
```

Where as
```
py3_image(
    name = "image",
    srcs = ["app.py"],
    layers = [
       requirement("flask"),
    ],
    main = "app.py",
)
```

Results in:
```
Traceback (most recent call last):
  File "/app/ev/tooling/py_flask/image.binary.runfiles/evertz/ev/tooling/py_flask/app.py", line 1, in <module>
    from flask import Flask
ImportError: cannot import name 'Flask'
```

**Comment by smukherj1** [comment] 2019-02-15 18:05
Took a look at this and was able to reproduce the issue using the tar attached by @calder. I dumped a snapshot of the filesystem of the images built by giving the pip requirements to deps vs layers.
In both images, I see the following directories in `/app/hello_image.binary.runfiles`:
```
__init__.py  
__main__  
pypi__Click_7_0  
pypi__Flask_1_0_2  
pypi__itsdangerous_1_1_0  
pypi__Jinja2_2_10  
pypi__MarkupSafe_1_1_0  
pypi__Werkzeug_0_14_1
```

In the image built with the dependencies specified to "deps", these directories have actual files in them. In the image built with the dependencies specified to "layers", these directories have symlinks that seem to point to invalid targets. For example, in the bad image we have:
```
/app/hello_image.binary.runfiles/pypi__Flask_1_0_2/flask/__main__.py -> /app/__main__/../pypi__Flask_1_0_2/flask/__main__.py
```

However, `/app/__main__` does not exist. It should be `/app/hello_image.binary.runtimes/__main__` instead. The resulting `/app/hello_image.binary.runtimes/__main__/../pypi__Flask_1_0_2/flask/__main__.py` does exist.

I think this symlinking is happening somewhere in https://github.com/bazelbuild/rules_docker/blob/28d52d57276e4fd3ea554b45321cf66f633cd46d/lang/image.bzl#L125. I'm not too familiar with this code so I'll have to dig more.

This may not actully fix this issue but is a definite issue I see in the image where flask fails to import

**Comment by smukherj1** [comment] 2019-02-21 14:50
Found the invalid symlink mapping is being generated here:

https://github.com/bazelbuild/rules_docker/blob/28d52d57276e4fd3ea554b45321cf66f633cd46d/lang/image.bzl#L175

Taking a look at the `layer_file_path` function here https://github.com/bazelbuild/rules_docker/blob/28d52d57276e4fd3ea554b45321cf66f633cd46d/lang/image.bzl#L104, we have

```python
def layer_file_path(ctx, f):
    return "/".join([ctx.attr.directory, ctx.workspace_name, f.short_path])
```

For the invalid target `/app/__main__/../pypi__Flask_1_0_2/flask/__main__.py`, the breakdown here is:
```
ctx.attr.directory: "/app"
ctx.workspace: "__main__"
f.short_path: "../pypi__Flask_1_0_2/flask/__init__.py"
```

So obviously the `ctx.workspace` part is erroneous here and the ".." in the beginning of the short_path is unnecessary. But I'm not sure if the issue here is in the implementation of layer_file_path or in the attributes of `f` which would mean an issue with the runfile objects in the given dependency to py_image generated by py_library or rules_python's pip stuff

**Comment by smukherj1** [comment] 2019-02-21 14:54
When I hack the layer_file_path to do this
```python
def layer_file_path(ctx, f):
    short_path = f.short_path
    return "/".join([ctx.attr.directory, short_path[3:]])
```

The resulting image works, i.e., the flask app runs successfully when the py_image is built with the dependencies specified to "layers".

**Comment by nlopezgi** [comment] 2019-02-22 15:18
I think we might a missing a `__main__` directory as the bazel runfiles tree structure expects it to exist in the image so that the path `/app/__main__/../` is valid. Not sure where in https://github.com/bazelbuild/rules_docker/blob/master/python/image.bzl that would need to be added though.

**Closed** 2019-03-21 16:05 UTC
Labels: bug
