### ISSUE TITLE
Incompatible Python toolchain

### ISSUE THREAD

**Issue by mdvorsky** [bazelbuild/rules_docker#1105] opened 2019-08-22 16:23 UTC
When I include `rules_docker` in my `WORKSPACE`, my default python toolchain suddenly changes and no longer works on MacOSX:

```
INFO: ToolchainResolution: Looking for toolchain of type @bazel_tools//tools/python:toolchain_type...
INFO: ToolchainResolution:   For toolchain type @bazel_tools//tools/python:toolchain_type, possible execution platforms and toolchains: {@bazel_tools//platforms:host_platform -> @io_bazel_rules_docker//toolchains/python:default_container_py_runtime_pair}
```

https://github.com/bazelbuild/rules_docker/blob/master/toolchains/python/BUILD#L29

```
py_runtime(
    name = "default_container_py3_runtime",
    interpreter_path = "/usr/bin/python3",
    python_version = "PY3",
)
```

```
$ ls /usr/bin/python3
ls: /usr/bin/python3: No such file or directory
```

The default python toolchain `bazel_tools//tools/python:_autodetecting_py_runtime_pair` which I get if I don't include `rules_docker`:

```
INFO: ToolchainResolution:   For toolchain type @bazel_tools//tools/python:toolchain_type, possible execution platforms and toolchains: {@bazel_tools//platforms:host_platform -> @bazel_tools//tools/python:_autodetecting_py_runtime_pair}
```

works correctly.

```
$ bazel version
Build label: 0.28.1-homebrew
Build target: bazel-out/darwin-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Fri Jul 19 16:09:50 2019 (1563552590)
Build timestamp: 1563552590
Build timestamp as int: 1563552590
```

**Comment by nlopezgi** [comment] 2019-08-22 16:28
This is likely a duplicate of https://github.com/bazelbuild/rules_docker/issues/1093. Closing but let me know to reopen if the pointed issue (and its recommended solution) does not work for you.

**Comment by nlopezgi** [comment] 2019-08-22 16:28
See also https://github.com/bazelbuild/rules_docker/issues/1087

**Comment by mdvorsky** [comment] 2019-08-22 17:37
Thank you!

I'm not sure I understand what is the recommended solution. Do I need to define my own python runtime and then use `--host_platform` and `--platform`? 

Just to clarify, my regular `py_binary` rules became broken, just by loading `rules_docker` rules, without even using `py_image`. I did not have to specify python runtime before I added `rules_docker`, I'm not even sure what should I set the python runtime to (we're using the WORKSPACE on different platforms, both MacOS and Linux) -- the bazel default works fine.

**Comment by mdvorsky** [comment] 2019-09-02 09:32
Everything works with empty WORKSPACE:

```
$ cat WORKSPACE
$ cat BUILD
py_binary(
    name = "test",
    srcs = ["test.py"]
)
$ cat test.py
print("OK")
$ bazel run test
...
OK
```

Things stop working when I add `_py_image_repos` to WORKSPACE.
```
$ cat > WORKSPACE
load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

# Download the rules_docker repository at release v0.9.0
http_archive(
    name = "io_bazel_rules_docker",
    sha256 = "e513c0ac6534810eb7a14bf025a0f159726753f97f74ab7863c650d26e01d677",
    strip_prefix = "rules_docker-0.9.0",
    urls = ["https://github.com/bazelbuild/rules_docker/releases/download/v0.9.0/rules_docker-v0.9.0.tar.gz"],
)

load(
    "@io_bazel_rules_docker//repositories:repositories.bzl",
    container_repositories = "repositories",
)
container_repositories()

load(
    "@io_bazel_rules_docker//python:image.bzl",
    _py_image_repos = "repositories",
)

_py_image_repos()

$ bazel run test
Traceback (most recent call last):
  File "/private/var/tmp/_bazel_marian/ba44d8afc44138a978df7eda7e2451ef/execroot/__main__/bazel-out/darwin-fastbuild/bin/test", line 340, in <module>
    Main()
  File "/private/var/tmp/_bazel_marian/ba44d8afc44138a978df7eda7e2451ef/execroot/__main__/bazel-out/darwin-fastbuild/bin/test", line 330, in Main
    os.execv(args[0], args)
FileNotFoundError: [Errno 2] No such file or directory: '/usr/bin/python3'

$ which python3
/miniconda3/bin/python3
$ which python
/miniconda3/bin/python
$ ls /usr/bin/python
/usr/bin/python
$ ls /usr/bin/python3
ls: /usr/bin/python3: No such file or directory
$ /usr/bin/python --version
Python 2.7.10
```

**Comment by horkyada** [comment] 2019-10-02 12:05
I'm unable to build py3 image (on mac) due to the same error:
```
ERROR: /private/var/tmp/_bazel_adam/9bcbc0b984736800f0018bcd9788713c/external/py3_image_base/image/BUILD:4:1: SHA256 external/py3_image_base/image/002.tar.gz.nogz.sha256 failed (Exit 1) sha256 failed: error executing command bazel-out/host/bin/external/bazel_tools/tools/build_defs/hash/sha256 bazel-out/darwin-fastbuild/bin/external/py3_image_base/image/002.tar.gz.nogz ... (remaining 1 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox
Traceback (most recent call last):
  File "bazel-out/host/bin/external/bazel_tools/tools/build_defs/hash/sha256", line 340, in <module>
    Main()
  File "bazel-out/host/bin/external/bazel_tools/tools/build_defs/hash/sha256", line 326, in Main
    ret_code = subprocess.call(args)
  File "/usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 323, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "/usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 1522, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/usr/bin/python3': '/usr/bin/python3'
```

**Comment by mdvorsky** [comment] 2019-10-02 15:17
Thank you @nlopezgi! I confirm that https://github.com/bazelbuild/rules_docker/pull/1173 fixes the issue I described above.

**Comment by nlopezgi** [comment] 2019-10-03 18:14
For record, https://github.com/bazelbuild/rules_docker/pull/1173 will permanently fix this issue. Before this PR it was not possible to run a py*_image from a host environment that did not have the py binary installed in the same location as in the py_image base container. Note if you do have python in a custom location inside the container it's still necessary to use a custom py_toolchain. However, this PR enables the default containerized py_toolchain to not interfere with the autodetected py_toolchain.

**Comment by horkyada** [comment] 2019-10-14 14:51
Hi, I updated `rules_docker` to `0.11` and I still get the error (in the Marian's example):

**Comment by nlopezgi** [comment] 2019-10-15 12:50
Can you run your build with these extra flags:
`--extra_execution_platforms=@local_config_platform//:host,@io_bazel_rules_docker//platforms:local_container_platform`
and let me know if that fixes the issue?
Toolchains are hard, and we're working with Bazel team to figure out what is the right way to do this. In the meantime, expect a bit of instability related to this use case.

**Comment by horkyada** [comment] 2019-10-15 13:13
Yes, with the flags it works. It works even with just `--extra_execution_platforms=@local_config_platform//:host`. Thank you

**Comment by nlopezgi** [comment] 2019-10-15 13:29
Thanks for the response. We're working to make this easier, for now, you can add the flag to your .bazelrc file to avoid having to write it in every command.

**Closed** 2021-04-18 02:09 UTC
Labels: Can Close?
