### ISSUE TITLE
Invalid ELF header - py_image with binary dependencies on OS X

### ISSUE THREAD

**Issue by darrengarvey** [bazelbuild/rules_docker#372] opened 2018-04-03 15:36 UTC
When running an image built with `py_image` on OS X, if a shared library is depended on, I'm unable to run the image.

I've put up a minimal test case here: https://github.com/darrengarvey/_bazel_py_image_test_case

I might be setting something up wrong here - I realise it's expecting a lot from bazel, especially with the use of `requirements()` automagically bringing in the postgres dependency.

However, I have no problem running images compiled from C++. Another thing that works fine is a `py_image` from python code that depends on compiled gRPC shared libraries.

**Comment by ynqa** [comment] 2018-06-06 05:27
It's looks like similar case of mine: #370

**Comment by ynqa** [comment] 2018-06-06 05:29
I guess that it's probably caused by compiling C/C++/Cython codes for OS X before building docker images.

**Comment by nlopezgi** [comment] 2018-06-25 14:31
Yes, this is most likely related to the library being compiled for OSx and then being used inside a linux docker image, which will generally not work (generally, bazel does not support cross OS compilation which is what you are trying to achieve here). You will need to make all the shared libraries also use the *_image rules (if possible) or, alternatively, you could try to run your build from inside a docker container (when running from a mac) so that the libraries get compiled for linux.

**Comment by FrancoisChastel** [comment] 2019-08-26 03:50
@nlopezgi is that issue is still around ? I face the same issue ! How do you suggest to do for example with `lxml` to be built with `py_image` ?

**Comment by smukherj1** [comment] 2019-08-26 12:31
Hi @FrancoisChastel,

Did you try @nlopezgi 's suggestion

> you could try to run your build from inside a docker container (when running from a mac) so that the libraries get compiled for linux.

**Comment by FrancoisChastel** [comment] 2019-08-27 03:28
Hi @smukherj1 
In my opinion working it around by simply using linux is not a solution at all, which let only the second one but I am not sure of how to achieve it ! Could you provide me an example with `lxml` or whatever is relevant in your opinion ? 
Thank you very much :)

**Comment by ccate** [comment] 2019-10-28 19:11
@nlopezgi I thought the https://docs.bazel.build/versions/master/platforms.html stuff was going to solve this problem. Is that not the case?

**Comment by nlopezgi** [comment] 2019-10-29 03:23
@FrancoisChastel,
Unfortunately we only own (and only have bandwidth) to support rules_docker and we cannot solve a problem that is related to how python rules and how Bazel works on a Mac. We do our best to provide a good experience on all platforms, but for this specific use case running inside a docker container will likely be your only option for some time. 
@ccate , yes, it will, we all hope. But afaik not all the pieces have landed yet. The key piece that is needed here is python rules that create work with platforms properly (i.e., for pip packages). Afaik we're not there yet. Once that happens, it should be "simple" for rules_docker to take advantage of the features.

 Keeping this open, but honestly, there's nothing we can do here other than recommend folks run things inside a container for this specific use case.

**Comment by surlyengineer** [comment] 2019-11-29 20:00
Is this still true?  If there's a particular way I can help drive this forward I'd be happy to contribute some time.  My particular use case is running a few services locally with Skaffold using bazel as its builder.  I'd prefer to not be running skaffold from inside a docker container if possible to avoid it.

**Comment by darrengarvey** [comment] 2019-11-29 20:46
@nlopezgi Appreciate keeping this open. It may not be a universal issue but it's not that unrealistic a use-case: using postgres from python...

> there's nothing we can do here other than recommend folks run things inside a container

Is there anything stopping bazel from running this inside a container if that's the only option? That's preferable (as a user) than a recommendation in the documentation - which if it exists I haven't seen.

**Comment by nlopezgi** [comment] 2019-11-30 00:57
> Is this still true? If there's a particular way I can help drive this forward I'd be happy to contribute some time. 

The fix for this is not in this repo, you can open an issue in the rules_python repo and we can figure out there if there is a way you can help

My particular use case is running a few services locally with Skaffold using bazel as its builder. I'd prefer to not be running skaffold from inside a docker container if possible to avoid it.

As mentioned above, this issue cannot be solved on this repo

**Comment by nlopezgi** [comment] 2019-11-30 01:00
> @nlopezgi Appreciate keeping this open. It may not be a universal issue but it's not that unrealistic a use-case: using postgres from python...
> 

I understand, but there is little we can do here


> > there's nothing we can do here other than recommend folks run things inside a container
> 
> Is there anything stopping bazel from running this inside a container if that's the only option? That's preferable (as a user) than a recommendation in the documentation - which if it exists I haven't seen.

I do not know sufficient details about what would impede rules_python from supporting this better. That probably does not mean running this inside a container natively. But you can open an issue in rules_python or Bazel repo to ask about multi platform build support and loop me there and I can provide more details.

**Comment by surlyengineer** [comment] 2019-11-30 04:22
Someone happened to open this a few days ago: https://github.com/bazelbuild/rules_python/issues/260 at a glance it looks like the same issue.

**Closed** 2021-04-18 02:10 UTC
Labels: Can Close?
