### ISSUE TITLE
Docker RUN used in Cloud documentation.

### ISSUE THREAD

**Issue by jsonschema** [bazelbuild/rules_docker#173] opened 2017-09-26 16:18 UTC
Google's documentation for [Building a Docker Image](https://cloud.google.com/endpoints/docs/grpc/docker-image) makes use of RUN:

```
FROM gcr.io/google_appengine/python

RUN apt-get update && \
    apt-get install -y python2.7 python-pip && \
    apt-get clean && \
    rm /var/lib/apt/lists/*_*

ADD . /app
WORKDIR /app

RUN pip install -r requirements.txt
ENTRYPOINT ["gunicorn", "-b", ":8080", "main:app"]
```

Sample Dockerfile at [python-docs-samples/endpoints/getting-started/Dockerfile.custom](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/master/endpoints/getting-started/Dockerfile.custom).

I've read through [Supporting RUN instructions?](https://github.com/bazelbuild/rules_docker/issues/90) - but it remains unclear to me how this works with `pip install`.

**Comment by mattmoor** [comment] 2017-09-26 16:52
(to rehash that thread a little bit)
The way Bazel builds Docker images is fundamentally different from the way just about everyone else builds Docker images.  In particular, we don't support `RUN` because of two main reasons:
1. Virtually everything folks do in `RUN` isn't reproducible.
1. The way the Docker daemon evaluates `RUN` is never reproducible.

This can be a bit of a pill for folks used to `Dockerfile`'s convenience, but if you can manage to live within these constraints you get a ton of nice properties that are virtually impossible with traditional methods.  These properties (and constraints) are largely projections of Bazel's principles.

---
Your real question seems to be: How do I make my Bazel application consume PIP dependencies?

That is a **great** question, and a useful feature independent of its use in Docker images!  I recently put together `bazelbuild/rules_python` to solve this looooooong-standing Bazel issue (in part because it was such a common ask from `rules_docker` users).

I think you'd be interested in seeing [this](https://github.com/bazelbuild/rules_k8s/pull/38) example.  It combines `bazelbuild/rules_python` to import PIP dependencies into Bazel, and then assembles a Python image using `py_image` from this repository.

The reason the sample isn't merged is because of [this](https://github.com/bazelbuild/rules_python/issues/17#issuecomment-331544148) issue, which has a pretty straightforward workaround.

**Closed by mattmoor** 2017-09-26 16:52 UTC

**Comment by fikriauliya** [comment] 2018-02-14 23:48
@mattmoor I have seen your example, please correct me if my understanding is incorrect:
- You run `pip install` in the host environment (in `WORKSPACE`)
- The generated files are included into docker image via `deps` param
- This way, we don't need `RUN` instruction as in `Dockerfile`

I have similar cases to run `npm install` and `bundle install`. Those are currently run in my `Dockerfile`. Learning from your approach, can I simple run `npm install` and `bundle install` in the host (in `WORKSPACE`) and copy the downloaded dependencies (`packages` folder in the case of `npm install`) to Docker via `deps`?

**Comment by mattmoor** [comment] 2018-02-14 23:54
`rules_nodejs` has an `npm_install` that works similarly to `pip_install`.  I'm not familiar with `bundle install`?

**Comment by fikriauliya** [comment] 2018-02-15 01:54
`bundle install` is to install Ruby dependency. Since it's not yet supported, I am thinking to create myself.
Any article to the recommended way to install external dependencies not managed by Bazel (e.g. pip, npm)? Or are my points above sufficiently correct?
