### ISSUE TITLE
Can we add support to bzlmod through Bazel central registry

### ISSUE THREAD

**Issue by rverma-nsl** [bazelbuild/rules_docker#2183] opened 2022-11-06 05:27 UTC
# 🚀 feature request

With the bzlmod support, the auto-configuration for docker toolchain helps in usage for even newbies like me.

### Description

The steps are pretty simple, but I don't know what are the test targets

```sh
❯ python3 ./tools/add_module.py
INFO: Getting module information from user input...
ACTION: Please enter the module name: rules_docker
ACTION: Please enter the module version: 0.25.0
ACTION: Please enter the compatibility level [default is 1]: 
ACTION: Please enter the URL of the source archive: https://github.com/bazelbuild/rules_docker/releases/download/v0.25.0/rules_docker-v0.25.0.tar.gz
ACTION: Please enter the strip_prefix value of the archive [default None]: rules_docker-0.25.0
ACTION: Do you want to add patch files? [y/N]: N
ACTION: Do you want to add a BUILD file? [y/N]: N
ACTION: Do you want to specify a MODULE.bazel file? [y/N]: N
ACTION: Do you want to specify dependencies for this module? [y/N]: N
ACTION: Do you want to specify an existing presubmit.yml file? (See https://github.com/bazelbuild/bazel-central-registry/tree/main#presubmityml) [y/N]: N
ACTION: Please enter a list of build targets you want to expose to downstream users, separated by `,`: container_repositories,container_deps,container_pull,container_image
ACTION: Do you have a test module in your source archive? [Y/n]: n
INFO: Saving module information to rules_docker.20221106-095208.json
INFO: You can use it via --input=rules_docker.20221106-095208.json
INFO: rules_docker is a new Bazel module...
ACTION: Please enter the homepage URL for this module: https://github.com/bazelbuild/rules_docker
```
### Describe the solution you'd like

Within the presubmit we need to add required test targets

Further we need to add dependencies if there any on the module, e.g. gazelle

**Comment by cfclrk** [comment] 2022-12-20 09:58
What/where is that `add_module.py` file you are referring to?

**Comment by tradergt** [comment] 2023-01-09 21:15
Probably here: https://github.com/bazelbuild/bazel-central-registry/blob/main/tools/add_module.py

**Comment by MarkusTeufelberger** [comment] 2023-03-06 09:34
See also #2116

**Comment by alexeagle** [comment] 2023-03-12 22:33
Dupe of #2165

**Closed by alexeagle** 2023-03-12 22:33 UTC
