### ISSUE TITLE
java_image doesn't work with runfiles

### ISSUE THREAD

**Issue by bjchambers** [bazelbuild/rules_docker#506] opened 2018-08-28 18:40 UTC
A `java_binary` target with `data` dependencies (either directly or indirectly) doesn't seem to work when converted to a `java_image` target. If used with `com.google.devtools.build.runfiles.Runfiles` to access the runfiles, it gives the following error:

```
Caused by: java.io.IOException: Cannot find runfiles: $RUNFILES_DIR and $JAVA_RUNFILES are both unset or empty
```

It looks like the `java_image` rule doesn't set the environment parameters. Is there some other mechanism for accessing data dependencies from within a `java_image`?

**Comment by nlopezgi** [comment] 2018-08-28 18:58
Thanks for opening this issue. 

Could you provide a bit more info about how to reproduce the error you are getting? 

My initial thought is that $RUNFILES_DIR and $JAVA_RUNFILES are make variables that should be properly expanded in the rules, and we might not be expanding them correctly atm (i.e., we recently had changes to expand args and location https://github.com/nlopezgi/rules_docker/commit/f5ed963f7411f07efd6b0bd8667fe89d6a05077b
https://github.com/nlopezgi/rules_docker/commit/115d891e359ea3097cd0bc1b32e1aaf8c580c455). 

If you could also try to send a PR with a fix (if these PRs are enough to get you on the right path) it would be awesome! (otherwise will try to get to take a detailed look as soon as I can once you send repro instructions)

**Comment by bjchambers** [comment] 2018-08-28 19:04
They are environment variables (https://github.com/bazelbuild/bazel/blob/master/tools/java/runfiles/Runfiles.java#L174) set by the Java wrapper (https://github.com/bazelbuild/bazel/blob/master/src/main/java/com/google/devtools/build/lib/bazel/rules/java/java_stub_template.txt#L140).

I'll try to put together a minimal repro and send it.

**Comment by bjchambers** [comment] 2018-08-28 19:42
Added two entries to testdata in this branch: https://github.com/bjchambers/rules_docker/tree/java-data-runfiles

When running `bazel run //testdata:java_runfiles_image` or `bazel run //testdata:java_runfiles_as_lib_image` the following error is printed:

```
Exception in thread "main" java.io.IOException: Cannot find runfiles: $RUNFILES_DIR and $JAVA_RUNFILES are both unset or empty
	at com.google.devtools.build.runfiles.Runfiles.getRunfilesDir(Runfiles.java:180)
	at com.google.devtools.build.runfiles.Runfiles.create(Runfiles.java:114)
	at com.google.devtools.build.runfiles.Runfiles.create(Runfiles.java:79)
	at examples.images.Runfiles.main(Runfiles.java:24)
```

It also adds two `java_binary` targets that demonstrate this should work -- when running `bazel run //testdata:java_runfiles_binary` or `bazel run //testdata:java_runfiles_as_lib_binary` it loads the contents of the file and prints `asdf`.

**Comment by bjchambers** [comment] 2018-08-28 19:51
It looks like there may be two separate issues here:

1. The `data` files (in this case `testdata/foo`) are not included in the runfiles within the images.
2. The environment variable `$RUNFILES_DIR` or `$JAVA_RUNFILES` is not set.

The latter seems pretty easy to fix (worst case, could even do it as an argument in the `java_image` rule, if necessary). The former seems trickier -- it would require gathering the transitive runfiles from all dependencies, I believe.

**Comment by bjchambers** [comment] 2018-08-28 22:07
Updated that branch with a commit that fixes the problem but increases the size of the image because it includes too much -- for instance local_jdk, etc. I'm not sure what a reasonable path forward is.

**Comment by bjchambers** [comment] 2018-09-04 16:02
@nlopezgi any thoughts on how to only pick up the necessary data_files? I could try to find the dependency that is adding the JVM dependencies, and explicitly list those as already available? 

If we can't make this work I may be able to work around the need by creating a separate layer with my specific data file, but it seems like making java_image and java_binary behave the same is desirable...

**Comment by nlopezgi** [comment] 2018-09-05 17:31
I'll also take some time to look at these vars, and if they indeed should be set as env vars or should be handled as other Bazel make variables and let you know about that as well soon.

**Comment by bjchambers** [comment] 2018-09-05 17:33
The tests in the branch that I shared may help. It uses the Bazel library for accessing the runfiles, and demonstrates that (1) if the ENV variable is not set, the utility fails as originally described (2) if the ENV variable is set but the files aren't found it simply fails to find the files and (3) if the ENV variable is set and the files are found, the utility (and test) works.

**Comment by nlopezgi** [comment] 2018-09-07 19:20
@bjchambers thanks again for reporting this issue. I have sent https://github.com/bazelbuild/rules_docker/pull/517 which will partially fix the issues you are having (it adds the data files to the container for java_image).
I still need to figure out:
- Fix for war_images data files (looks like they have the same issue as java_image)
- what value I should set for the JAVA_RUNFILES env variable. 

Will look at this again next week. If you have time in the meantime, you can test if my change, once submitted, works for you to at least load the right files in the image (I'm particularly interested in knowing if the file structure for the data files is the one expected by the java command being executed)

**Comment by bjchambers** [comment] 2018-09-07 20:18
I patched your change into my code (see branch https://github.com/bjchambers/rules_docker/tree/java-data-runfiles-2) and it fixes cases where the data dependency is directly listed in the java_image. However, any java_library may have a data dependency, and it doesn't recursively pull those data dependencies in.

Specifically, in the branch I sent out, your change (plus my ENV variable setting) makes `bazel run //testdata:java_runfiles_image` work (where the java_image has a data dependency) but `bazel run //testdata:java_runfiles_as_lib_image` does not work (java_image depends on a java_library with the data dependency).

**Comment by nlopezgi** [comment] 2018-09-10 14:20
thanks for the clarifications, I'll try a different strategy sometime this week (i.e., its going to be hard to get transitive deps w/o bringing in the entire local_jdk)

**Comment by bjchambers** [comment] 2018-09-10 15:51
Looking at the code for the layer, the thought I had was to list all transitive deps in `unavailable`, and the transitive deps of local_jdk in `available`.

Then the `unavailable -= available` will exclude the deps of the local_jdk, and only those files that are `unavailable` are added to the layer. I got stuck though on being able to figure out the transitive deps of the local_jdk (wasn't sure where to get that target).

**Comment by nlopezgi** [comment] 2018-09-20 20:00
Hi @bjchambers , thanks again for your clarifications and patience.
The big issue is I dont think its possible to be able to figure out what deps are part of local_jdk. The only viable solution is to not use the local_jdk at all, but doing that might cause issues for current customers that do not have a version of java installed in their host environments.

However, I finally was able to get something working that (i hope) will satisfy your use case without causing any regressions for current users. Could you please see my latest update in https://github.com/bazelbuild/rules_docker/pull/517, and try it out and let me know if it works for you (apologies for all the extra env vars / flags testing this requires)?

**Comment by pcj** [comment] 2018-09-21 16:15
Note that as a workaround the `pkg_tar` rule has an option `include_runfiles` that allows one to build a tarball with transitive runfiles included.  Then, add that tarball to your image.

**Comment by bjchambers** [comment] 2018-09-21 19:35
Thanks Nicolas, I'll take a look tonight or over the weekend. That sounds like about what I got stuck on too when trying to patch it. I wonder if there is a way to get bazel to allow accessing the local_jdk that is being used, or something like that.

Alternatively, I thought of having the java_image rule only enable the transitive runfiles if an explicit `jdk = ...` target was passed. Then it could include transitive runfiles of the java_image rule, but none of the transitive runfiles of the JDK target. Not sure how feasible either of those are -- would it be worth asking in one of the bazel lists?

**Comment by nlopezgi** [comment] 2018-09-21 19:53
thanks @pcj for your comment. @bjchambers, could you try the alternative proposed by @pcj ? If it works, although not ideal, would be a better solution than all this bending around to work with the local_jdk we're trying.

@bjchambers, wrt trying other alternatives to get around the local_jdk, we could try to ask in one of the bazel lists, but I'm very certain there is no way around having the local_jdk be a dep of these rules other than passing javabase flags atm (I'm an active contributor to java_rules discussions / roadmap). I know there is current work happening in the java_rules world (specifically related to toolchains, and also lots happening wrt default jdks to use for host/target env) which will make if feasible to declare that the java_xx rules produced by the java_image rule should use a different jdk than the target jdk used by default by java_xx rules. This would make it trivial to get the behavior we need (all deps except local_jdk) without these flags. My big concern about the flags is that its an error prone mechanism, and not using them does not result in failures but results in very large images, which will be a bad customer experience. 

At this point my preference would be to try out @pcj's solution and, if it works, continue using that until java_rules are not so deeply tied to the @local_jdk. I'm also willing to get something like what i sent in my PR (feature is env var guarded, requires use of javabase to avoid dragging in local_jdk) to get this working for you, even if its code that will be removed once proper platform/toolchains are supported on Java rules.

**Comment by bjchambers** [comment] 2018-09-21 20:15
Perhaps I failed to explain what I was trying to do. I wasn't trying to ask
bazel for "all deps except local jdk". I was trying to ask bazel for "all
deps of the jdk". Since we already have a way of enumerating all deps of a
target, this seems like it should just require a way of asking which target
corresponds to the jdk.

Then we can enumerate all the deps (which would include the jdk) and just
skip those that were enumerated as deps of the jdk.

That said, I think my use case can be handled as a direct dependency of the
Java image, so if it isn't currently possible the earlier work around
should work. I was just trying to make it align with java_binary rules as
much as possible.

**Comment by bjchambers** [comment] 2018-09-25 18:52
Sorry I haven't yet had time to patch this in and run the tests. It may be faster for you to patch the tests I wrote demonstrating the use of java runfiles and see if it works.

Overall, the best middle ground may be to use the original patch you had that only supported `data` dependencies directly on the `java_image` rule. This will work for me, and won't require as much gymnastics. That plus the environment changes in my branch should make the "direct" dependency tests in my branch pass.

We can include the tests for indirect data dependencies from my branch as "these should work but don't currently" and file a bug against bazel to make it possible to retrieve "all data dependencies except for the JDK" (or to make the JDK determinable so we can exclude it).

**Comment by bjchambers** [comment] 2018-09-25 23:11
Actually, I think I figured out how to make it work. I added the Java toolchain as an attribute, based on this example https://github.com/bazelbuild/bazel/blob/master/tools/build_rules/java_rules_skylark.bzl#L117.

That in turn lets my require all of the data dependencies, but mark the JDK files as already available, which excludes them from the image.

See https://github.com/bazelbuild/rules_docker/pull/530

**Comment by nlopezgi** [comment] 2018-09-26 13:04
Thanks a lot for working on this so patently. The solution that you propose is the right one, its simple and uses the java toolchain in the correct way. Sending back comments on the PR. Thanks for coming up with this solution!

**Comment by nlopezgi** [comment] 2018-10-01 14:47
Fixed in https://github.com/bazelbuild/rules_docker/pull/530

**Closed by nlopezgi** 2018-10-01 14:47 UTC
