### ISSUE TITLE
Add capabilities to the binary in the container

### ISSUE THREAD

**Issue by sustrik** [bazelbuild/rules_docker#752] opened 2019-03-21 12:08 UTC
I want to build a binary, put it into a image and set a capability (net_admin) on it.

1. container_image doesn't allow for arbitrary run commands, so I can't do it that way.
2. In theory, I could tar the binary with --xattrs, but tar_pkg doesn't provide that option. Not sure if container_image extracts tars with --xattrs.
3. Even if 2. worked, it means I would have to build a binary with the capability. I could have a genrule for that, but it would require sudo. Consequently, I would have to run the entire build toolchain under sudo :/

Is there a preferred way to do this?

**Comment by alex1545** [comment] 2019-03-22 16:54
Hello @sustrik and thank you for your interest in rules_docker.

1. It's correct that `container_image` doesn't allow for run commands because this rule doesn't run any containers in the process of building docker images. If you really want to run a command inside a container while you build an image you can try using the [container_run_and_commit](https://github.com/GoogleContainerTools/base-images-docker/blob/91965492ca08c8308de43877c9d608bc812fd143/util/run.bzl#L225) rule. See [here](https://github.com/bazelbuild/rules_k8s/blob/81d9171657f360f0295061eadbfe7fef157fb42d/images/gcloud-bazel/BUILD) for an example on how it can be used together with a `container_image` target.
But for your use case, I think the preferred way would be to just have a simple script that sets file capabilities, where you copy that script into your image (using the `files` attribute in the `container_image` target) and run that script when starting a new container.

2. As you mentioned about your second approach, this is not a good solution as it will require you running your build command with sudo, because you would be setting file capabilities in your host environment as opposed to setting those in a running container instead.

**Comment by vishalgarg837** [comment] 2019-08-04 13:41
@alex1545 I am facing same issue and i tried first option suggested by you but it's taking lot of time to build the image. It also gives following message:
```
Pushing an image based on a tarball can be very expensive.  If the image is the output of a docker_build, consider dropping the '.tar' extension. If the image is checked in, consider using docker_import instead.
```

Here is my actual issue: https://github.com/bazelbuild/rules_docker/issues/1049

Can you suggest something?

**Comment by alex1545** [comment] 2019-08-06 17:35
Hi @vishalgarg837,
Unfortunately, this is the expected behavior having such performance decline when having to run a container and recording its state (with `docker commit`) in the process of building an image. This is how images are built with Dockerfiles and in rare circumstances we have to do the same.
I experimented for some time with file capabilities and was only able to get the desired result when setting the capabilities inside a running container. If you can find other ways to copy files into the image being built to preserve their capabilities (without running a container and doing `docker commit`), I could help you from there.

**Comment by nlopezgi** [comment] 2019-08-09 18:32
Closing, please let me know if anything is pending here to reopen.

**Closed by nlopezgi** 2019-08-09 18:32 UTC

**Comment by kprakasam** [comment] 2021-04-04 21:11
Adding flag to `--xattrs --xattrs-include=security.capability` during tar and untar  retains the capabilities, though these flags require sudo lot of builds happen on containers with root privileges so it may be worth adding this feature.
