### ISSUE TITLE
build_tag_filters not working as expected

### ISSUE THREAD

**Issue by tejal29** [bazelbuild/rules_docker#269] opened 2017-12-20 21:03 UTC
Hi, 
I want to disable building and testing a target on OSX. 
I have added the following in [rules_docker.json](https://github.com/tejal29/rules_docker/blob/build_tag_filter_repro/.ci/rules_docker.json) 
```
    {
        "node": "darwin-x86_64",
        "parameters": {
            "tests": ["//tests/docker/... except //tests/docker/..."],
            "build_tag_filters": ["-needs_xz"]
        }
```
and tests/docker:deb_image_with_dpkgs has the tag.
```
container_image(
    name = "deb_image_with_dpkgs",
    debs = [
        "//testdata:pkg1.deb",
        "//testdata:pkg2.deb",
        ":busybox-static_ubuntu1_amd64.deb",
    ],
    tags = ["needs_xz"],
)
```
However, i still see the target being built on OSX node.
Any advise would be appreciated.

Thanks
Tejal

**Comment by tejal29** [comment] 2017-12-20 21:07
Build error https://ci.bazel.io/blue/organizations/jenkins/PR%2Frules_docker/detail/rules_docker/350/pipeline/25

**Comment by philwo** [comment] 2018-01-02 13:18
Hi @tejal29,

the target will always be built if it is a dependency of anything else in your build, so you have to make sure that nothing that you build and test depends on it. I think this might be what's happening here.

The build_tag_filters and test_tag_filters can be helpful to exclude the targets and tests that rely on `deb_image_with_dpkgs`.

Hope that helps, let me know if you need more information.

Cheers,
Philipp

**Comment by ash2k** [comment] 2018-02-28 05:26
I think there is a bug in `rules_docker`. Seems like `tags` from the `go_image` rule are not "propagated" to the underlying rules it generates and hence there is still a dependency on `go_binary` and hence everything is built anyway even with `--build_tag_filters=-exclude_from_tests` option. Here is the snippet that is reproducing the behaviour:
```bzl
go_binary(
    name = "ops_race",
    embed = [":go_default_library"],
    race = "on",
    tags = [
        "exclude_from_tests",
    ],
    visibility = ["//visibility:public"],
)

go_image(
    name = "container_race",
    binary = ":ops_race",
    tags = [
        "exclude_from_tests",
    ],
    visibility = ["//visibility:public"],
)
```
If I comment out `go_image` and specify `--build_tag_filters=-exclude_from_tests` then that `go_binary` is not built (as expected). But if `go_image` is there then both are built even with `build_tag_filters`.
/cc @mattmoor

**Comment by mattmoor** [comment] 2018-02-28 05:39
We expect to pass-through most kwargs to `go_binary`, and are sensitive to a limited few (e.g. `visibility`).  `tags` is not one of the ones we're sensitive to today.

I believe @ash2k is correct and we'd want logic similar to `visibility` for `tags` in the assorted `lang_image` rules.

**Comment by ash2k** [comment] 2018-03-02 09:35
I can confirm that the issue is fixed now. Can be closed.

**Closed** 2018-03-02 15:17 UTC

**Comment by tejal29** [comment] 2018-03-19 16:59
Thanks!
I will add the tests back.
