### ISSUE TITLE
container_push no longer prints digests

### ISSUE THREAD

**Issue by luna-duclos** [bazelbuild/rules_docker#1325] opened 2019-12-17 10:44 UTC
We recently upgraded to rules_docker 0.12.1 and container_push no longer prints out the digest of any pushed imaged, forcing us to manually cat the digest file to figure out what it is, which is inconvenient.
This is likely related to the change to the go based containerregistry rather than the python one.

Is it possible this can be readded ?

**Comment by smukherj1** [comment] 2019-12-18 02:36
Duplicate of #1215. Please see that issue for the new recommended way of obtaining the digest instead of depending on the stdout. Let me know if that doesn't solve your issue and I'll re-open to discuss alternatives.

**Closed by smukherj1** 2019-12-18 02:36 UTC

**Comment by luna-duclos** [comment] 2019-12-18 13:27
We have rules that build multiple docker images and manually catting the .digest file as a user is very very clumsy, would strongly prefer if we could avoid that somehow.

**Comment by nlopezgi** [comment] 2019-12-18 14:11
Hi @luna-duclos ,
Your use case definitely sounds like one where having custom rules to process the digest is the right solution. Depending on stdout of these rules is not recommended and the output of these rules is not part of their API.
