### ISSUE TITLE
File name length limit

### ISSUE THREAD

**Issue by hrvolapeter** [bazelbuild/rules_docker#1848] opened 2021-05-07 11:11 UTC
# 🐞 bug report

### Affected Rule

 The issue is caused by the rule: 
container_image

### Is this a regression?

 Unknown

### Description

 A clear and concise description of the problem...
File name length of 90 characters with combination of "directory" property causes file to be put into "/" instead of specified "directory"

## 🔬 Minimal Reproduction
https://github.com/hrvolapeter/bazel_rules_docker_bug_repro

File aaa is put in correct folder while aaaaa* is put in root
## 🌍  Your Environment

**Operating System:**

<pre>
  <code>
MacOS 11.3
  </code>
</pre>

**Output of `bazel version`:**

<pre>
  <code>
Bazelisk version: development
Build label: 4.0.0
Build target: bazel-out/darwin-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Thu Jan 21 07:38:50 2021 (1611214730)
Build timestamp: 1611214730
Build timestamp as int: 1611214730
  </code>
</pre>

**Rules_docker version:**

<pre>
  <code>
rules_docker-0.17.0
  </code>
</pre>

**Comment by gravypod** [comment] 2021-05-09 17:38
I've been doing some debugging on this. I've added a test case for this issue and tracked it down to here: https://github.com/bazelbuild/rules_docker/blob/a98e680636e1e1703c13f3fb22dce10998e328d4/container/archive.py#L417

I don't know much about the Python tarfile module implementation and I'm not able to use my step through debugger. I'm going to keep debugging this but I may opt for a bit of a hacky solution here. Even if I just create a new TarInfo() object and manually copy all the fields from one to the other the code starts working as intended. I'd much rather understand what is actually broken here.

I've been thinking about rewriting this code as it's difficult for me to debug but I would like to find a resolution that works for your use case before I undertake that.

**Comment by hrvolapeter** [comment] 2021-05-09 18:11
Hi @gravypod, I've managed to get around the problem with symlinks, the file names were just slightly longer than the limit. Unfortunately I've been packaging static webserver and we need to stick with the filenames so renaming wasn't really an option.

I did a bit more debugging so maybe I can share my findings:
- we had the exact same image in Dockerfile and I'm just rewriting it to bazel, dockerfile doesn't have problem with the names
- when I review the produced tarfiles all paths seems to be ok and starting with relative path
- I tried just renaming the file to avoid some missing permissions or file properties, the problem seems to be related only to the name length
- importing the produced tar in docker and running it has wrong paths
- importing and exporting tar to docker produces tar with wrong file paths
- tar [v7](https://www.gnu.org/software/tar/manual/html_section/Formats.html) implementation has filename length limit 99 chars, but it's unlikely docker, python is producing this version
- I've tried pushing the produced tar in OCI format to GCR and run it in Cloud Run, still has wrong paths

Let me know if I can help with some investigations but at this point I'm pretty much out of ideas

**Comment by gravypod** [comment] 2021-05-09 22:05
@hrvolapeter thank you very much for the "99 char" pointer! With that I was able to find out what this was caused by. If you've got some free time would you be willing to test out https://github.com/bazelbuild/rules_docker/pull/1850 in your use case?

**Comment by gravypod** [comment] 2021-05-23 14:48
@hrvolapeter, we've merged that branch to master. I'm closing this issue for now. Feel free to reopen if the issue persists.

**Closed by gravypod** 2021-05-23 14:48 UTC
